export const FETCH_ACCOUNTBALANCES_REQUEST = "FETCH_ACCOUNTBALANCES_REQUEST";
export const FETCH_ACCOUNTBALANCES_SUCCESS = "FETCH_ACCOUNTBALANCES_SUCCESS";
export const FETCH_ACCOUNTBALANCES_FAILURE = "FETCH_ACCOUNTBALANCES_FAILURE";

export const SET_ACCOUNTBALANCE_REQUEST = "SET_ACCOUNTBALANCE_REQUEST";
export const SET_ACCOUNTBALANCE_SUCCESS = "SET_ACCOUNTBALANCE_SUCCESS";
export const SET_ACCOUNTBALANCE_FAILURE = "SET_ACCOUNTBALANCE_FAILURE";
