export const FETCH_ACCOUNTBALANCES_REQUEST = "FETCH_ACCOUNTBALANCES_REQUEST";
export const FETCH_ACCOUNTBALANCES_SUCCESS = "FETCH_ACCOUNTBALANCES_SUCCESS";
export const FETCH_ACCOUNTBALANCES_FAILURE = "FETCH_ACCOUNTBALANCES_FAILURE";

export const ADD_ACCOUNTBALANCE_REQUEST = "ADD_ACCOUNTBALANCE_REQUEST";
export const ADD_ACCOUNTBALANCE_SUCCESS = "ADD_ACCOUNTBALANCE_SUCCESS";
export const ADD_ACCOUNTBALANCE_FAILURE = "ADD_ACCOUNTBALANCE_FAILURE";

export const DELETE_ACCOUNTBALANCE_REQUEST = "DELETE_ACCOUNTBALANCE_REQUEST";
export const DELETE_ACCOUNTBALANCE_SUCCESS = "DELETE_ACCOUNTBALANCE_SUCCESS";
export const DELETE_ACCOUNTBALANCE_FAILURE = "DELETE_ACCOUNTBALANCE_FAILURE";
