export const FETCH_REPEATINGTRANSACTIONS_REQUEST =
  "FETCH_REPEATINGTRANSACTIONS_REQUEST";
export const FETCH_REPEATINGTRANSACTIONS_SUCCESS =
  "FETCH_REPEATINGTRANSACTIONS_SUCCESS";
export const FETCH_REPEATINGTRANSACTIONS_FAILURE =
  "FETCH_REPEATINGTRANSACTIONS_FAILURE";

export const ADD_REPEATINGTRANSACTION_REQUEST =
  "ADD_REPEATINGTRANSACTION_REQUEST";
export const ADD_REPEATINGTRANSACTION_SUCCESS =
  "ADD_REPEATINGTRANSACTION_SUCCESS";
export const ADD_REPEATINGTRANSACTION_FAILURE =
  "ADD_REPEATINGTRANSACTION_FAILURE";

export const DELETE_REPEATINGTRANSACTION_REQUEST =
  "DELETE_REPEATINGTRANSACTION_REQUEST";
export const DELETE_REPEATINGTRANSACTION_SUCCESS =
  "DELETE_REPEATINGTRANSACTION_SUCCESS";
export const DELETE_REPEATINGTRANSACTION_FAILURE =
  "DELETE_REPEATINGTRANSACTION_FAILURE";
