name: CI for Full-Stack Application

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-node-

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Run client linting
        working-directory: client
        run: npm run lint

      - name: Run client tests
        working-directory: client
        run: npm run test

      - name: Build client application
        working-directory: client
        run: npm run build

  server:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-node-

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Run server linting
        working-directory: server
        run: npm run lint

      - name: Run server tests
        working-directory: server
        run: npm run test

